package com.example.myapplication;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class Db {
    public static void main(String[] args) {
        // to run database java -cp ../lib/hsqldb.jar org.hsqldb.Server -database.0 file:studydb -dbname.0 studydb
        try (Connection conn = DatabaseUtil.getConnection();
             Statement stmt = conn.createStatement()) {
            String sql = "CREATE TABLE users (" +
                    "id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "username VARCHAR(255) NOT NULL, " +
                    "password VARCHAR(255) NOT NULL)";
            stmt.executeUpdate(sql);
            System.out.println("Table created successfully.");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
